# Generated by Django 2.0.5 on 2018-06-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryCode_text', models.CharField(max_length=2)),
                ('countryName_text', models.CharField(max_length=200)),
            ],
        ),
    ]
