# Generated by Django 2.0.5 on 2018-06-04 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countryinfo',
            old_name='countryCode_text',
            new_name='country_code',
        ),
        migrations.RenameField(
            model_name='countryinfo',
            old_name='countryName_text',
            new_name='country_name',
        ),
    ]
