# Generated by Django 2.0.5 on 2018-06-05 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateinfo',
            name='countryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.CountryInfo'),
        ),
    ]
